#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/device-simulation-dotnet"

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# To avoid hardcoding the version in multiple places, it's stored in a file
APP_VERSION=$(cat "$APP_HOME/version")

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    dotnet restore
    dotnet build --configuration $CONFIGURATION
}

build_docker_image() {
    check_dependency_docker

    cd $APP_HOME

    rm -fR out/docker
    rm -fR WebService/bin/Docker
    rm -fR SimulationAgent/bin/Docker

    mkdir -p out/docker/webservice
    mkdir -p out/docker/simulationagent

    dotnet publish WebService      --configuration $CONFIGURATION --output bin/Docker
    dotnet publish SimulationAgent --configuration $CONFIGURATION --output bin/Docker

    cp -pR WebService/bin/Docker/*       out/docker/webservice/
    cp -pR SimulationAgent/bin/Docker/*  out/docker/simulationagent/

    cp scripts/docker/.dockerignore              out/docker/
    cp scripts/docker/Dockerfile                 out/docker/
    cp scripts/docker/content/run.sh             out/docker/

    cd out/docker/
    docker build --tag "$DOCKER_IMAGE:$APP_VERSION" --squash --compress --label "Tags=azure,iot,pcs,simulation,.NET" .
}

compile
build_docker_image

set +e
