#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/device-simulation-dotnet"

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

# Whether to update the "latest" tag of the Docker image
BUILD_LATEST="no"

confirm_version() {
    echo "Building version $APP_VERSION"
    read -r -p "Do you want to update the 'latest' version too? [y/N] " response
    response=${response,,} # tolower
    if [[ $response =~ ^(no|n| ) ]] | [ -z $response ]; then
        BUILD_LATEST="no"
    else
        BUILD_LATEST="yes"
    fi
}

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    dotnet restore
    dotnet build --configuration $CONFIGURATION
}

build_docker_image() {
    check_dependency_docker

    cd $APP_HOME

    rm -fR out/docker
    rm -fR WebService/bin/Docker
    rm -fR SimulationAgent/bin/Docker

    mkdir -p out/docker/webservice
    mkdir -p out/docker/simulationagent

    dotnet publish WebService      --configuration $CONFIGURATION --output bin/Docker
    dotnet publish SimulationAgent --configuration $CONFIGURATION --output bin/Docker

    cp -pR WebService/bin/Docker/*       out/docker/webservice/
    cp -pR SimulationAgent/bin/Docker/*  out/docker/simulationagent/

    cp scripts/docker/.dockerignore              out/docker/
    cp scripts/docker/Dockerfile                 out/docker/
    cp scripts/docker/content/run.sh             out/docker/

    cd out/docker/

    if [[ $BUILD_LATEST == "no" ]]; then
        docker build --tag "$DOCKER_IMAGE:$APP_VERSION" --squash --compress --label "Tags=azure,iot,pcs,simulation,.NET" .
    else
        docker build --tag "$DOCKER_IMAGE:$APP_VERSION" --tag "$DOCKER_IMAGE:latest" --squash --compress --label "Tags=azure,iot,pcs,simulation,.NET" .
    fi

    echo "Run './scripts/docker/publish' to publish the image to the registry"
}

confirm_version
compile
build_docker_image

set +e
