#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/device-simulation-dotnet"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"

# To avoid hardcoding the version in multiple places, it's stored in a file
APP_VERSION=$(cat "$APP_HOME/version")

docker push $DOCKER_IMAGE:$APP_VERSION

set +e
