#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/device-simulation-dotnet:0.1-SNAPSHOT"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    echo "Starting Device Simulation ..."
    docker run -it -p $PCS_DEVICESIMULATION_WEBSERVICE_PORT:8080 \
        -e "PCS_DEVICESIMULATION_WEBSERVICE_PORT=8080" \
        -e "PCS_IOTHUBMANAGER_WEBSERVICE_URL=$PCS_IOTHUBMANAGER_WEBSERVICE_URL" \
        "$DOCKER_IMAGE"
}

run_container

set +e
