#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

compile() {
    check_dependency_nuget
    check_dependency_msbuild

    cd $APP_HOME
    nuget restore
    msbuild /m /p:Configuration=Debug
    msbuild /m /p:Configuration=Release
}

compile_in_sandbox() {
    cd $APP_HOME
    ./scripts/compile-in-sandbox
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    compile_in_sandbox
else
    compile
fi

set +e
