#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    dotnet restore
    dotnet build --configuration Debug
    dotnet build --configuration Release
}

compile_in_sandbox() {
    cd $APP_HOME
    ./scripts/compile-in-sandbox
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    compile_in_sandbox
else
    compile
fi

set +e
