#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"
cd $APP_HOME

check_dependencies() {
    set +e

    TEST=$(which nuget)
    if [[ -z "$TEST" ]]; then
        echo "ERROR: 'nuget' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
        exit 1
    fi

    TEST=$(which msbuild)
    if [[ -z "$TEST" ]]; then
        echo "ERROR: 'msbuild' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
        exit 1
    fi
    set -e
}

failed() {
    echo "Build failed"
    exit 1
}

compile() {
    nuget restore
    msbuild /m /p:Configuration=Debug
    msbuild /m /p:Configuration=Release
}

check_dependencies
compile
