#!/usr/bin/env bash

DOCKER_IMAGE="azureiotpcs/device-simulation-dotnet:0.1-SNAPSHOT"

echo "Starting web service at: http://localhost:8080"

set -e
docker run -it -p 8080:8080 -e "PCS_IOTHUB_CONN_STRING=$PCS_IOTHUB_CONN_STRING" "$DOCKER_IMAGE"
