#!/usr/bin/env bash

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run() {
    check_dependency_dotnet

    cd $APP_HOME
    echo "Building..."
    dotnet restore --verbosity=quiet
    dotnet build --configuration $CONFIGURATION --verbosity=quiet

    ./scripts/env-vars-check

    echo "Starting simulation agent and web service..."
    dotnet run --configuration $CONFIGURATION --project SimulationAgent/*.csproj & \
        dotnet run --configuration $CONFIGURATION --project WebService/*.csproj --background && \
        fg
}

run_in_sandbox() {
    cd $APP_HOME
    ./scripts/run-in-sandbox
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    run_in_sandbox
else
    run
fi

set +e
